name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: install deps
      run: |
        # install app deps
        npm install
        # install build deps
        npm install -g @vercel/ncc
    - name: build
      run: |
        rm dist/index.js
        make
  main-branch-check:
    runs-on: ubuntu-latest
    steps:
    - name: Main branch check
      if: always() && github.ref != 'refs/heads/main' 
      uses: jaymzh/main-branch-check-action@main
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        main_branch: "main"
        workflow_ref: ${{ github.workflow_ref }}
